#!/bin/sh

file="/etc/passwd"

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
	echo "$f1\t$f3\t$f6"
done < "$file"

# IFS	Internal File Separator, a delimeter for read
# IFS=: Sets the delimiber to ':' character
# read outputs to the files listed afterward	f1 f2 f3 f4 f5 f6 f7
